# Generated by Django 4.0.6 on 2022-08-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0002_alter_services_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
