# Generated by Django 4.0.6 on 2022-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0003_rename_forms_form_rename_services_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='RequestForm',
        ),
    ]
