# Generated by Django 4.0.6 on 2022-08-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0004_rename_form_requestform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='services',
        ),
        migrations.AddField(
            model_name='requestform',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='nst_electric.service'),
        ),
    ]
