# Generated by Django 4.0.6 on 2022-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0005_remove_requestform_services_requestform_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
