# Generated by Django 4.0.6 on 2022-08-28 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0008_alter_requestform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'Слишком много символов', 'required': 'Введите имя'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(291000000), django.core.validators.MaxValueValidator(449999999)]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='services',
            field=models.ForeignKey(error_messages={'required': 'Введите имя'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='nst_electric.service'),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='surname',
            field=models.CharField(error_messages={'max_length': 'Слишком много символов', 'required': 'Введите имя'}, max_length=20),
        ),
    ]
