# Generated by Django 4.0.6 on 2022-08-28 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0009_alter_requestform_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='number',
            field=models.IntegerField(error_messages={'MaxValueValidator': 'Введите правильный номер', 'MinValueValidator': 'Введите правильный номер', 'required': 'Введите правильный номер телефона'}, validators=[django.core.validators.MinValueValidator(291000000), django.core.validators.MaxValueValidator(449999999)]),
        ),
    ]
