# Generated by Django 4.0.6 on 2022-08-29 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0010_alter_requestform_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='surname',
        ),
        migrations.AddField(
            model_name='requestform',
            name='additional_information',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(291000000), django.core.validators.MaxValueValidator(449999999)]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='nst_electric.service'),
        ),
    ]
