# Generated by Django 4.0.6 on 2022-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0011_remove_requestform_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='number',
            field=models.CharField(max_length=9),
        ),
    ]
