# Generated by Django 4.0.6 on 2022-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0012_alter_requestform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='additional_information',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
