# Generated by Django 4.0.6 on 2022-08-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0013_alter_requestform_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='additional_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
