# Generated by Django 4.0.6 on 2022-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0016_alter_cleanservice_price_alter_draftservice_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('name_surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestForm',
        ),
    ]
