# Generated by Django 4.0.6 on 2022-08-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0017_reviews_delete_requestform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
