# Generated by Django 4.0.6 on 2022-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0019_stagework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Navigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150, null=True)),
                ('menu_navigate', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
