# Generated by Django 4.0.6 on 2022-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0020_advantages_navigate_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_class', models.CharField(max_length=20)),
                ('p_tag', models.CharField(max_length=100)),
            ],
        ),
    ]
