# Generated by Django 4.0.6 on 2022-09-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0021_ourservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurServices',
        ),
    ]
