# Generated by Django 4.0.6 on 2022-09-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0023_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
