# Generated by Django 4.0.6 on 2022-09-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0025_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='cleanservice',
            options={'verbose_name': 'Чистые работы', 'verbose_name_plural': 'Чистые работы'},
        ),
        migrations.AlterModelOptions(
            name='draftservice',
            options={'verbose_name': 'Грязные работы', 'verbose_name_plural': 'Грязные работы'},
        ),
        migrations.AlterModelOptions(
            name='legalservice',
            options={'verbose_name': 'Работы с юр.лицами', 'verbose_name_plural': 'Работы с юр.лицами'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
