# Generated by Django 4.0.6 on 2022-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nst_electric', '0026_delete_service_alter_cleanservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigate',
            name='href',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
